// <auto-generated />
namespace WebApplication_FitToFast.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changePurchaseHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changePurchaseHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201510161258551_changePurchaseHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
